name: Provisionar Tabela DynamoDB

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Escolha a ação: apply ou destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      branch:
        description: "Informe a branch a ser utilizada"
        required: true
        default: "main"

jobs:
  terraform:
    name: Executar Terraform DynamoDB
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backstage/dynamoDB

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        run: terraform init

      - name: Validar Terraform
        run: terraform validate

      - name: Executar Terraform Plan
        run: terraform plan -input=false

      - name: Executar Apply ou Destroy
        run: |
          if [ "${{ github.event.inputs.action }}" = "apply" ]; then
            terraform apply -auto-approve
          else
            terraform destroy -auto-approve
          fi
