name: Terraform Firestore Deployment

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Escolha a ação a ser executada"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    name: Executar Terraform no Firestore
    runs-on: ubuntu-latest

    env:
      GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar autenticação com GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Inicializar Terraform
        working-directory: backstage/gcp/firestore
        run: terraform init

      - name: Validar Terraform
        working-directory: backstage/gcp/firestore
        run: terraform validate

      - name: Executar Terraform Plan
        working-directory: backstage/gcp/firestore
        run: terraform plan -var="gcp_project_id=${{ env.GOOGLE_PROJECT }}" -var="gcp_region=us-central1"

      - name: Executar Terraform Apply ou Destroy
        if: github.event.inputs.action == 'apply'
        working-directory: backstage/gcp/firestore
        run: terraform apply -auto-approve -var="gcp_project_id=${{ env.GOOGLE_PROJECT }}" -var="gcp_region=us-central1"

      - name: Executar Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        working-directory: backstage/gcp/firestore
        run: terraform destroy -auto-approve -var="gcp_project_id=${{ env.GOOGLE_PROJECT }}" -var="gcp_region=us-central1"

      - name: Send log to InfluxDB via Fluent Bit
        if: always() # Garante execução mesmo se o job falhar
        run: |
          curl --location '${{ secrets.FLUENT_BIT_URL }}' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Basic ${{ secrets.FLUENT_BIT_AUTH_BA }}' \
          --data "{
            \"service\": \"github-actions\",
            \"workflow\": \"lambda-provisioning\",
            \"job\": \"terraform-${{ inputs.action }}\",
            \"status\": \"${{ job.status }}\",
            \"branch\": \"${GITHUB_REF_NAME}\",
            \"autor\": \"${GITHUB_ACTOR}\",
            \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
          }"
