name: Terraform - GCP ML Infra

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Escolha a ação a ser executada: apply ou destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      branch:
        description: "Branch para executar o Terraform"
        required: true
        default: "main"

jobs:
  terraform:
    name: Executar Terraform
    runs-on: ubuntu-latest

    env:
        GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        TF_ACTION: ${{ github.event.inputs.action }}
        TF_WORKING_DIR: backstage/gcp/ml-infra

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Instalar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GOOGLE_PROJECT }}
          service_account_key: ${{ env.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Inicializar Terraform
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Executar Terraform Plan
        if: env.TF_ACTION == 'apply'
        run: terraform plan -input=false
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Executar Terraform Apply
        if: env.TF_ACTION == 'apply'
        run: terraform apply -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Executar Terraform Destroy
        if: env.TF_ACTION == 'destroy'
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TF_WORKING_DIR }}
