name: EC2 Provisioning

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Escolha a ação: apply ou destroy"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      instance_type:
        description: "Tipo da instância EC2 (e.g., t2.micro)"
        required: true
        default: "t2.micro"
      ami:
        description: "ID da AMI para inicializar a instância"
        required: true
        default: "ami-0a590ca28046d073e"
      key_name:
        description: "Nome da chave SSH"
        required: true
        default: "my-generated-key"
      environment:
        description: "Nome do ambiente (e.g., dev, prod)"
        required: true
        default: "dev"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6

    - name: Initialize Backend
      run: terraform init -backend-config="bucket=seu-bucket-terraform" \
                          -backend-config="key=terraform/state/global.tfstate" \
                          -backend-config="region=us-east-1" \
                          -backend-config="encrypt=true" \
                          -backend-config="dynamodb_table=terraform-lock-table"
      working-directory: ./terraform

    - name: Initialize Terraform for EC2
      run: terraform -chdir=./modules/ec2 init

    - name: Terraform Action
      run: |
        if [ "${{ github.event.inputs.action }}" == "apply" ]; then
          terraform -chdir=./modules/ec2 apply -auto-approve \
            -var="instance_type=${{ github.event.inputs.instance_type }}" \
            -var="ami=${{ github.event.inputs.ami }}" \
            -var="key_name=${{ github.event.inputs.key_name }}" \
            -var="environment=${{ github.event.inputs.environment }}";
        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          terraform -chdir=./modules/ec2 destroy -auto-approve \
            -var="instance_type=${{ github.event.inputs.instance_type }}" \
            -var="ami=${{ github.event.inputs.ami }}" \
            -var="key_name=${{ github.event.inputs.key_name }}" \
            -var="environment=${{ github.event.inputs.environment }}";
        else
          echo "Ação inválida: ${GITHUB_EVENT_INPUTS_ACTION}" && exit 1;
        fi
